SELECT TITLE
FROM PEOPLE JOIN STARS ON PEOPLE.ID = STARS.PERSON_ID JOIN MOVIES ON MOVIES.ID = STARS.MOVIE_ID 
WHERE NAME = "Johnny Depp" 
INTERSECT
SELECT TITLE
FROM PEOPLE JOIN STARS ON PEOPLE.ID = STARS.PERSON_ID JOIN MOVIES ON MOVIES.ID = STARS.MOVIE_ID
WHERE NAME = "Helena Bonham Carter";